### ISSUE TITLE
obtainUserAccessToken fails with HTTP 411

### ISSUE THREAD

**Issue by NMichas** [ebx/ebx-linkedin-sdk#439]
Hello, I'm trying to obtain the user access token with:
```
LinkedInClient client = new DefaultLinkedInClient(Version.DEFAULT_VERSION);
LinkedInClient.AccessToken newAccessToken = client.obtainUserAccessToken(clientId, clientSecret, redirectURI, code);
```
But fails with:
```
Caused by: com.echobox.api.linkedin.exception.LinkedInNetworkException: A network error occurred while trying to communicate with LinkedIn: LinkedIn request failed(HTTP status code 411)
	at com.echobox.api.linkedin.client.DefaultLinkedInClient.makeRequestAndProcessResponse(DefaultLinkedInClient.java:716) ~[ebx-linkedin-sdk-8.0.0.jar:na]
	at com.echobox.api.linkedin.client.DefaultLinkedInClient.makeRequestFull(DefaultLinkedInClient.java:581) ~[ebx-linkedin-sdk-8.0.0.jar:na]
	at com.echobox.api.linkedin.client.DefaultLinkedInClient.obtainUserAccessToken(DefaultLinkedInClient.java:420) ~[ebx-linkedin-sdk-8.0.0.jar:na]
```

It seems the client doesn't set Content-Length; is there something I may be missing here?

Thanks!

**Comment by djjashton** [comment]
Hi MMichas,

Thank you for raising this issue.

If you would to raise a PR to add this API you are more than welcome to by following the [contributions guide](https://github.com/ebx/ebx-linkedin-sdk/blob/master/CONTRIBUTING.md).

**Comment by NMichas** [comment]
Hey, I'm afraid I'm not using ebx-linkedin-sdk anymore, I'll close this issue.
